// Datos de productos
export const productsData = [
  {
    id: 1,
    name: 'Running Sneakers',
    price: 89.99,
    image: '/img/heroimg1.png',
    category: 'Deportivo',
    gender: 'male',
    promotion: true,
    createdAt: '2024-04-01',
    discount: 20,
  },
  {
    id: 2,
    name: 'Stylish Sneakers',
    price: 79.99,
    image: '/img/heroimg2.png',
    category: 'Casual',
    gender: 'female',
    promotion: false,
    createdAt: '2024-04-03',
    discount: 0,
  },
  {
    id: 3,
    name: 'Sport Pro Sneakers',
    price: 99.99,
    image: '/img/heroimg1.png',
    category: 'Deportivo',
    gender: 'male',
    promotion: true,
    createdAt: '2024-03-28',
    discount: 20,
  },
  {
    id: 4,
    name: 'Urban Casual Shoes',
    price: 69.99,
    image: '/img/heroimg2.png',
    category: 'Casual',
    gender: 'female',
    promotion: false,
    createdAt: '2024-04-02',
    discount: 0,
  },
  {
    id: 5,
    name: 'Pro Running Sneakers',
    price: 129.99,
    image: '/img/heroimg1.png',
    category: 'Deportivo',
    gender: 'male',
    promotion: true,
    createdAt: '2024-04-04',
    discount: 25,
  },
  {
    id: 6,
    name: 'Pro Running Sneakers',
    price: 129.99,
    image: '/img/heroimg1.png',
    category: 'Deportivo',
    gender: 'male',
    promotion: true,
    createdAt: '2024-04-04',
    discount: 25,
  },
    {
      id: 7,
      name: 'Trail Running Shoes',
      price: 109.99,
      image: '/img/trail1.png',
      category: 'Deportivo',
      gender: 'unisex',
      promotion: true,
      createdAt: '2024-04-05',
      discount: 15,
    },
    {
      id: 8,
      name: 'Elegant Leather Shoes',
      price: 149.99,
      image: '/img/leather1.png',
      category: 'Formal',
      gender: 'male',
      promotion: false,
      createdAt: '2024-03-30',
      discount: 0,
    },
    {
      id: 9,
      name: 'Comfortable Sandals',
      price: 49.99,
      image: '/img/sandals1.png',
      category: 'Casual',
      gender: 'female',
      promotion: true,
      createdAt: '2024-04-02',
      discount: 10,
    },
    {
      id: 10,
      name: 'High-Performance Cleats',
      price: 199.99,
      image: '/img/cleats1.png',
      category: 'Deportivo',
      gender: 'male',
      promotion: true,
      createdAt: '2024-03-25',
      discount: 30,
    },
    {
      id: 11,
      name: 'Classic Loafers',
      price: 89.99,
      image: '/img/loafers1.png',
      category: 'Formal',
      gender: 'unisex',
      promotion: false,
      createdAt: '2024-04-01',
      discount: 0,
    },
    {
      id: 12,
      name: 'Kids Running Shoes',
      price: 59.99,
      image: '/img/kids1.png',
      category: 'Deportivo',
      gender: 'kids',
      promotion: true,
      createdAt: '2024-04-03',
      discount: 20,
    },
  
];